### ISSUE TITLE
Don't know how to make

### ISSUE THREAD

**Issue by GoatGod64** [Ontwikseltsaar/smo-practice#9]
Can someone help me out by making a tutorial video?

**Comment by Ontwikseltsaar** [comment]
Do you want to build this mod, or do you want to install this mod?

**Comment by GoatGod64** [comment]
build it

**Comment by Ontwikseltsaar** [comment]
Are you on Windows or Linux, or something else? Did you check the prerequisites? For devkitPro you can use this link: https://devkitpro.org/wiki/Getting_Started.

What happens when you try to run the makefile?

**Comment by GoatGod64** [comment]
I'm sorry for bothering you but but I managed to build it

**Comment by Ontwikseltsaar** [comment]
Glad to hear!
